kind: Service
apiVersion: v1
metadata:
  name: helidon-mp-example
  labels:
    app: helidon-mp-example
spec:
  type: NodePort
  selector:
    app: helidon-mp-example
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-mp-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-mp-example
  template:
    metadata:
      labels:
        app: helidon-mp-example
        version: v1
    spec:
      containers:
      - name: helidon-mp-example
        image: helidon-mp-example
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
